### PR TITLE
View all certificates without supplying group_id or email

### PR DESCRIPTION
**Pull request by andreibondarev**
This PR provides a way to call Accredible::Credential.view_all() without supplying group_id or email

Per: https://accrediblecredentialapi.docs.apiary.io/#reference/credentials/all-credentials/view-many-credentials

### CODE REVIEW

**Comment by andreibondarev** [comment]
@sublimecoder @alanheppenstall

**Comment by andreibondarev** [comment]
@sublimecoder @alanheppenstall Have you had a chance to glance over this?

**Comment by sublimecoder** [comment]
LGTM 👍

**Comment by andreibondarev** [comment]
@sublimecoder I think it might make sense to also tag and release a new gem version.

**Pull request merged**
